# Generated by Django 2.1 on 2019-06-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_userextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('articles', models.ManyToManyField(related_name='tags', to='article.Article')),
            ],
        ),
    ]
