# Generated by Django 2.1 on 2019-06-20 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('page', models.IntegerField()),
                ('price', models.FloatField(validators=[django.core.validators.MaxValueValidator(limit_value=1000)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=16)),
                ('telephone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('1[34578]]\\d{9}')])),
            ],
        ),
    ]
