# Generated by Django 2.1 on 2019-06-24 02:02

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
